version: "3"

services:
  web:
    image: tetracon/pingservices:2.17
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.2"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:9000"
    networks:
      - webnet
networks:
  webnet: