# start with a scratch (no layers)
#FROM scratch
FROM scratch
# copy our static linked library
COPY pingservices pingservices

# tell we are exposing our service on port 8080
EXPOSE 9000

# run it!
CMD ["./pingservices"] 